title: Sutoneline Blog
description: Record of learning 
author: sut
github: https://sutonline.github.io/
about: 
disqus_shortname: blog
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"


urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/agusmakmun
    - text: XML Feed
      url: /feed.xml

url: "https://sutonline.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist